<html DOCTYPE!>
<head>
	<link rel="stylesheet" href="css/bootstrap.css">
	<link rel="stylesheet" href="css/main.css">
</head>
<body>
	<div class="container">
      
	  <form class="form-signin" 
			action="saveChanges.php<?php if($newuser) : ?>?id=new<?php endif ?>" 
			method="post">
        <h2 class="form-signin-heading">Профиль</h2>
		<?php if ($isadmin) : ?>
			<p>id <?=$user['id'] ?></p>
        <?php endif ?>
		<input type="text" id="id" class="form-control" name="id" hidden='true' value="<?=$user['id'] ?>">
		<label for="login" class="control-label">Login</label>
		<input type="login" id="login" class="form-control" name="login" value="<?=$user['login'] ?>" title="Login" required autofocus>
		<label for="fullname" class="control-label">ФИО</label>
        <input type="text" id="fullname" class="form-control" name="fullname" value="<?=$user['fullname'] ?>">
		<label for="email" class="control-label">E-mail</label>
		<input type="email" id="email" class="form-control" name="email" value=<?=$user['e-mail'] ?>>
		<label for="role" class="control-label">Администратор / пользователь</label>
		<select required id="role" class="form-control" name="role" value=<?=$user['role'] ?>>
			<option value="user">user</option>
			<option value="admin">admin</option>
		</select>
		<label for="password" class="control-label">Пароль</label>
		<input type="password" id="password" class="form-control" name="password" value="<?=$user['password'] ?>" required>
		<br>
        <button class="btn btn-lg" type="button" onclick="history.back();">Закрыть</button>
		<?php if ($isadmin && !$me) : ?>
			<button class="btn btn-lg" type="submit" name="delete" value="delete">Удалить</button>
			<button class="btn btn-lg btn-primary" type="submit" name="save" value="save">Сохранить</button>
		<?php endif ?>
		<?php if ($me) : ?>
			<button class="btn btn-lg btn-primary" type="submit" name="save" value="save">Сохранить</button>
		<?php endif ?>
      </form>

    </div>
	<script src="js/jquery-3.1.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
</body>