<html DOCTYPE!>
<head>
	<link rel="stylesheet" href="css/bootstrap.css">
</head>
<body>
<div class="navbar">
	<a href="profile.php">настройки профиля</a>
	<a href="index.php">выйти</a>
</div>
<?php if (!empty($users)) : ?>
	
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th><a href="?sort=login">login</a></th>
      <th>e-mail</th>
      <th><a href="?sort=username">Username</a></th>
	  <th><a href="?sort=role">Role</a></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($users as $user) : ?>
		<tr>
			<td><?=$user['id']?></td>
			<td><a href="#" data-toggle="modal" data-target="#mymodal"><?=$user['login']?></a></td>
			<td><?=$user['login']?></td>
			<td><?=$user['e-mail']?></td>
			<td><?=$user['fullname']?></td>
			<td><?=$user['role']?></td>
		</tr>
	<?php endforeach ?>
  </tbody>
</table>	
<?php endif ?>

<div class="modal fade" id="mymodal" tadindex="-1" role="dialog" aria-label="mymodal" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="mymodallabel">modal title</h5>
				<button class="close" type="button" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
</div>
<script src="js/bootstrap.min.js"></script> 
</body>
</html>