<html DOCTYPE!>
<head>
	<link rel="stylesheet" href="css/bootstrap.css">
</head>
<body>
<div class="navbar">
	<a href="editProfile.php?id=me">мой профиль</a>
	<?php if($isadmin) : ?>
		<a href="editProfile.php?id=new">добавить пользователя</a>
	<?php endif ?>
	<a href="index.php">выйти</a>
</div>
<?php if (!empty($users)) : ?>
	
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th><a href="?sort=login">login</a></th>
      <th>e-mail</th>
      <th><a href="?sort=username">Username</a></th>
	  <th><a href="?sort=role">Role</a></th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($users as $user) : ?>
		<tr>
			<td><?=$user['id']?></td>
			<td><a href="editProfile.php?id=<?=$user['id']?>"><?=$user['login']?></a></td>
			<td><?=$user['e-mail']?></td>
			<td><?=$user['fullname']?></td>
			<td><?=$user['role']?></td>
		</tr>
	<?php endforeach ?>
  </tbody>
</table>	
<?php endif ?>


<script src="js/bootstrap.min.js"></script> 
</body>
</html>